const SUCCESS  = 200;

const CREATED = 201;

const FORBIDEN  = 403;

const UNAUTHORIZED = 401;

const NOT_FOUND  = 404;

const BAD_REQUEST = 400;

const SERVER_ERROR = 500;

const NOT_CREATED = 409

export { SUCCESS, CREATED, NOT_CREATED , FORBIDEN, UNAUTHORIZED, NOT_FOUND, BAD_REQUEST, SERVER_ERROR }

